// Proves the Dart DCF engine matches the Python one.
//
// The app recomputes locally while a slider is dragged, which means the same
// arithmetic now lives in two languages. These tests exist so the two cannot
// drift apart silently:
//
//   1. The reference case - Apple with the spreadsheet's assumptions must
//      give $160.99, the same figure test_dcf.py asserts against
//      AAPL_DCF_Model.xlsx.
//   2. Parity against recorded backend responses across many assumption
//      combinations, regenerated by tools/generate_parity_fixtures.py.
//   3. The honesty note, whose wording is duplicated in Dart so it can update
//      mid-drag, must reproduce the backend's string exactly.

import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;

import 'package:flutter_test/flutter_test.dart';

import 'package:dcf_app/dcf_engine.dart';

/// Relative comparison: the figures span per-share dollars to billions, so a
/// single absolute tolerance would be either useless or unfair.
void expectClose(double actual, double expected, {double rel = 1e-9, String? reason}) {
  final scale = math.max(1.0, expected.abs());
  final diff = (actual - expected).abs();
  expect(
    diff / scale < rel,
    isTrue,
    reason: reason ??
        'expected $expected, got $actual (relative diff ${diff / scale})',
  );
}

void main() {
  group('reference case: AAPL_DCF_Model.xlsx', () {
    // The spreadsheet's own inputs, identical to test_dcf.py.
    const base = BaseYearData(
      revenue: 416161,
      totalDebt: 98657,
      cash: 132420,
      shares: 14773.3,
      currentPrice: 296.42,
    );
    const assumptions = DcfAssumptions(
      revenueGrowth: 0.06,
      operatingMargin: 0.32,
      taxRate: 0.16,
      daPct: 0.028,
      capexPct: 0.031,
      nwcPct: 0.03,
      wacc: 0.085,
      terminalGrowth: 0.03,
      projectionYears: 5,
    );

    late DcfResult result;
    setUp(() => result = runDcf(base, assumptions));

    test('intrinsic value per share is \$160.99', () {
      expect(result.intrinsicValuePerShare, closeTo(160.99, 0.01));
    });

    test('revenue projection matches the spreadsheet', () {
      expect(result.years.first.revenue, closeTo(441131, 1));
      expect(result.years.last.revenue, closeTo(556917, 1));
    });

    test('unlevered free cash flow matches', () {
      expect(result.years.first.ufcf, closeTo(116503, 1));
      expect(result.years.last.ufcf, closeTo(147083, 1));
    });

    test('discounting matches', () {
      expect(result.years.first.discountFactor, closeTo(0.922, 0.001));
      expect(result.pvUfcfSum, closeTo(512705, 1));
    });

    test('Gordon growth terminal value matches', () {
      expect(result.terminalValue, closeTo(2754462, 1));
      expect(result.pvTerminalValue, closeTo(1831842, 1));
    });

    test('equity bridge matches', () {
      expect(result.enterpriseValue, closeTo(2344547, 1));
      expect(result.equityValue, closeTo(2378310, 1));
    });

    test('implied downside and terminal share match', () {
      expect(result.upsideDownside, closeTo(-0.457, 0.001));
      expect(result.tvPctOfEv, closeTo(0.781, 0.001));
    });
  });

  group('input guards', () {
    const base = BaseYearData(
      revenue: 1000,
      totalDebt: 100,
      cash: 100,
      shares: 100,
      currentPrice: 10,
    );

    test('terminal growth at or above WACC is refused', () {
      expect(
        () => runDcf(
            base,
            const DcfAssumptions(
              revenueGrowth: 0.05,
              operatingMargin: 0.2,
              taxRate: 0.2,
              daPct: 0.03,
              capexPct: 0.03,
              nwcPct: 0.02,
              wacc: 0.08,
              terminalGrowth: 0.08,
            )),
        throwsA(isA<DcfInputError>()),
      );
    });

    test('a zero share count is refused rather than producing infinity', () {
      expect(
        () => runDcf(
            const BaseYearData(
                revenue: 1000,
                totalDebt: 0,
                cash: 0,
                shares: 0,
                currentPrice: 10),
            const DcfAssumptions(
              revenueGrowth: 0.05,
              operatingMargin: 0.2,
              taxRate: 0.2,
              daPct: 0.03,
              capexPct: 0.03,
              nwcPct: 0.02,
              wacc: 0.08,
              terminalGrowth: 0.02,
            )),
        throwsA(isA<DcfInputError>()),
      );
    });
  });

  group('parity with the Python backend', () {
    late Map<String, dynamic> fixture;
    late List<dynamic> cases;

    setUpAll(() {
      final file = File('test/fixtures/parity_cases.json');
      expect(file.existsSync(), isTrue,
          reason: 'Run tools/generate_parity_fixtures.py with the backend up.');
      fixture = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
      cases = fixture['cases'] as List<dynamic>;
    });

    test('fixture covers a range of assumption combinations', () {
      expect(cases.length, greaterThanOrEqualTo(10));
    });

    test('every recorded case reproduces to within rounding', () {
      final failures = <String>[];

      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final label = c['label'] as String;

        final base =
            BaseYearData.fromJson(c['base_year'] as Map<String, dynamic>);
        final assumptions = DcfAssumptions.fromMap(
          (c['assumptions'] as Map<String, dynamic>)
              .map((k, v) => MapEntry(k, (v as num).toDouble())),
        );
        final expected = c['expected'] as Map<String, dynamic>;

        try {
          final result = runDcf(base, assumptions);

          void check(String field, double actual) {
            final want = (expected[field] as num).toDouble();
            final scale = math.max(1.0, want.abs());
            if ((actual - want).abs() / scale >= 1e-9) {
              failures.add('$label / $field: backend $want, dart $actual');
            }
          }

          check('intrinsic_value_per_share', result.intrinsicValuePerShare);
          check('upside_downside', result.upsideDownside);
          check('enterprise_value', result.enterpriseValue);
          check('equity_value', result.equityValue);
          check('terminal_value', result.terminalValue);
          check('pv_terminal_value', result.pvTerminalValue);
          check('pv_ufcf_sum', result.pvUfcfSum);
          check('tv_pct_of_ev', result.tvPctOfEv);
        } on DcfInputError catch (e) {
          failures.add('$label: dart engine refused inputs the backend accepted ($e)');
        }
      }

      expect(failures, isEmpty,
          reason: 'Dart and Python engines diverged:\n${failures.join('\n')}');
    });

    test('the honesty note reproduces the backend wording exactly', () {
      // Wording is duplicated in Dart so it can update mid-drag; this is the
      // guard against the two copies drifting apart.
      final mismatches = <String>[];

      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final assumptions = (c['assumptions'] as Map<String, dynamic>)
            .map((k, v) => MapEntry(k, (v as num).toDouble()));
        final expected = c['expected'] as Map<String, dynamic>;

        final built = buildHonestyNote(
          intrinsicValuePerShare:
              (expected['intrinsic_value_per_share'] as num).toDouble(),
          companyName: c['company_name'] as String,
          wacc: assumptions['wacc']!,
          terminalGrowth: assumptions['terminal_growth']!,
          equityRiskPremium: assumptions['equity_risk_premium'],
        );

        if (built != c['note']) {
          mismatches.add('${c['label']}:\n  backend: ${c['note']}\n  dart:    $built');
        }
      }

      expect(mismatches, isEmpty,
          reason: 'Honesty note wording drifted:\n${mismatches.join('\n\n')}');
    });
  });

  group('money and percent formatting matches Python', () {
    test('thousands separators and 2dp', () {
      expect(formatMoney(160.99), '160.99');
      expect(formatMoney(1234.5), '1,234.50');
      expect(formatMoney(1234567.891), '1,234,567.89');
      expect(formatMoney(0), '0.00');
      expect(formatMoney(-42.5), '-42.50');
    });

    test('percentages to 2dp', () {
      expect(formatPercent2(0.1059), '10.59%');
      expect(formatPercent2(0.025), '2.50%');
      expect(formatPercent2(0), '0.00%');
    });
  });
}
