// Proves the Dart DCF engine matches the Python one.
//
// The app recomputes locally while a slider is dragged, which means the same
// arithmetic now lives in two languages. These tests exist so the two cannot
// drift apart silently:
//
//   1. The reference case - Apple with the spreadsheet's assumptions must
//      give $160.99, the same figure test_dcf.py asserts against
//      AAPL_DCF_Model.xlsx.
//   2. Parity against recorded backend responses across many assumption
//      combinations, regenerated by tools/generate_parity_fixtures.py.
//   3. The honesty note, whose wording is duplicated in Dart so it can update
//      mid-drag, must reproduce the backend's string exactly.

import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;

import 'package:flutter_test/flutter_test.dart';

import 'package:dcf_app/dcf_engine.dart';

/// Relative comparison: the figures span per-share dollars to billions, so a
/// single absolute tolerance would be either useless or unfair.
void expectClose(double actual, double expected, {double rel = 1e-9, String? reason}) {
  final scale = math.max(1.0, expected.abs());
  final diff = (actual - expected).abs();
  expect(
    diff / scale < rel,
    isTrue,
    reason: reason ??
        'expected $expected, got $actual (relative diff ${diff / scale})',
  );
}

void main() {
  group('reference case: AAPL_DCF_Model.xlsx', () {
    // The spreadsheet's own inputs, identical to test_dcf.py.
    const base = BaseYearData(
      revenue: 416161,
      totalDebt: 98657,
      cash: 132420,
      shares: 14773.3,
      currentPrice: 296.42,
    );
    const assumptions = DcfAssumptions(
      revenueGrowth: 0.06,
      operatingMargin: 0.32,
      taxRate: 0.16,
      daPct: 0.028,
      capexPct: 0.031,
      nwcPct: 0.03,
      wacc: 0.085,
      terminalGrowth: 0.03,
      projectionYears: 5,
    );

    late DcfResult result;
    setUp(() => result = runDcf(base, assumptions));

    test('intrinsic value per share is \$160.99', () {
      expect(result.intrinsicValuePerShare, closeTo(160.99, 0.01));
    });

    test('revenue projection matches the spreadsheet', () {
      expect(result.years.first.revenue, closeTo(441131, 1));
      expect(result.years.last.revenue, closeTo(556917, 1));
    });

    test('unlevered free cash flow matches', () {
      expect(result.years.first.ufcf, closeTo(116503, 1));
      expect(result.years.last.ufcf, closeTo(147083, 1));
    });

    test('discounting matches', () {
      expect(result.years.first.discountFactor, closeTo(0.922, 0.001));
      expect(result.pvUfcfSum, closeTo(512705, 1));
    });

    test('Gordon growth terminal value matches', () {
      expect(result.terminalValue, closeTo(2754462, 1));
      expect(result.pvTerminalValue, closeTo(1831842, 1));
    });

    test('equity bridge matches', () {
      expect(result.enterpriseValue, closeTo(2344547, 1));
      expect(result.equityValue, closeTo(2378310, 1));
    });

    test('implied downside and terminal share match', () {
      expect(result.upsideDownside, closeTo(-0.457, 0.001));
      expect(result.tvPctOfEv, closeTo(0.781, 0.001));
    });
  });


  group('a horizon the user chose', () {
    // The projection length is a slider between 5 and 10 years now, and the
    // app previews it locally as the slider moves. The local engine therefore
    // has to change shape with it, not just change a number.
    const base = BaseYearData(
      revenue: 416161,
      totalDebt: 98657,
      cash: 132420,
      shares: 14773.3,
      currentPrice: 296.42,
    );
    DcfAssumptions at(int years) => DcfAssumptions(
          revenueGrowth: 0.06,
          operatingMargin: 0.32,
          taxRate: 0.16,
          daPct: 0.028,
          capexPct: 0.031,
          nwcPct: 0.03,
          wacc: 0.085,
          terminalGrowth: 0.03,
          projectionYears: years,
        );

    for (final years in const [5, 6, 7, 8, 9, 10]) {
      test('$years years: the projection, discounting and bridge all follow',
          () {
        final r = runDcf(base, at(years));

        expect(r.years.length, years);
        expect(r.years.last.period, years);

        for (final y in r.years) {
          expectClose(y.revenue, 416161 * math.pow(1.06, y.period).toDouble());
          expectClose(y.discountFactor, 1 / math.pow(1.085, y.period).toDouble());
        }

        // Gordon growth hangs off whichever year turned out to be last.
        final last = r.years.last;
        expectClose(r.terminalValue, last.ufcf * 1.03 / (0.085 - 0.03));
        expectClose(r.pvTerminalValue, r.terminalValue * last.discountFactor);

        expectClose(r.pvUfcfSum,
            r.years.fold<double>(0, (sum, y) => sum + y.pvUfcf));
        expectClose(r.enterpriseValue, r.pvUfcfSum + r.pvTerminalValue);
        expectClose(r.equityValue, r.enterpriseValue + 132420 - 98657);
        expectClose(r.intrinsicValuePerShare, r.equityValue / 14773.3);
      });
    }

    test('the default is untouched by the horizon being adjustable', () {
      expectClose(runDcf(base, at(5)).intrinsicValuePerShare, 160.99,
          rel: 1e-4);
    });

    test('a longer horizon leans less on the terminal value', () {
      final five = runDcf(base, at(5));
      final ten = runDcf(base, at(10));
      expect(ten.tvPctOfEv, lessThan(five.tvPctOfEv));
    });

    test('the slider carries the horizon through a copyWith override', () {
      final moved = at(5).copyWith({'projection_years': 10});
      expect(moved.projectionYears, 10);
      expect(runDcf(base, moved).years.length, 10);
    });
  });

  group('the optional growth fade', () {
    // Mirrors test_dcf.py. The two engines have to agree not just on the
    // figure but on the shape of the glide, because this one previews what
    // that one confirms.
    const base = BaseYearData(
      revenue: 10000,
      totalDebt: 2000,
      cash: 1000,
      shares: 1000,
      currentPrice: 50,
    );
    DcfAssumptions at({
      bool fade = false,
      int startYear = 3,
      String pattern = fadeLinear,
      double growth = 0.18,
      int years = 10,
    }) =>
        DcfAssumptions(
          revenueGrowth: growth,
          operatingMargin: 0.30,
          taxRate: 0.21,
          daPct: 0.05,
          capexPct: 0.06,
          nwcPct: 0.05,
          wacc: 0.10,
          terminalGrowth: 0.025,
          projectionYears: years,
          fadeEnabled: fade,
          fadeStartYear: startYear,
          fadePattern: pattern,
        );

    test('off by default, and then every year grows at the one rate', () {
      expect(const DcfAssumptions(
        revenueGrowth: 0.1, operatingMargin: 0.3, taxRate: 0.2, daPct: 0.05,
        capexPct: 0.05, nwcPct: 0.05, wacc: 0.1, terminalGrowth: 0.025,
      ).fadeEnabled, isFalse);
      expect(growthPath(at()), List<double>.filled(10, 0.18));
    });

    test('with it off the whole result is untouched', () {
      final plain = runDcf(base, at());
      final off = runDcf(base, at(fade: false));
      expect(off.intrinsicValuePerShare, plain.intrinsicValuePerShare);
      expect(off.pvUfcfSum, plain.pvUfcfSum);
      expect(off.terminalValue, plain.terminalValue);
    });

    for (final pattern in const [fadeLinear, fadeExponential]) {
      test('$pattern: holds flat, then glides to the terminal rate', () {
        final path = growthPath(at(fade: true, pattern: pattern));
        expect(path.length, 10);
        expect(path.take(3), everyElement(0.18));
        expect(path.last, 0.025, reason: 'exactly, not approximately');
        for (var i = 3; i < path.length; i++) {
          expect(path[i], lessThanOrEqualTo(path[i - 1]));
        }
      });
    }

    test('exponential falls faster at first', () {
      final lin = growthPath(at(fade: true, pattern: fadeLinear));
      final exp = growthPath(at(fade: true, pattern: fadeExponential));
      expect(exp[3], lessThan(lin[3]));
      expect(exp.last, lin.last);
    });

    test('exponential falls back to the straight line where a ratio cannot '
        'mean anything', () {
      final exp = growthPath(
          at(fade: true, growth: 0, pattern: fadeExponential, years: 6));
      final lin =
          growthPath(at(fade: true, growth: 0, pattern: fadeLinear, years: 6));
      expect(exp, lin);
    });

    test('a fade with nowhere to run is simply flat', () {
      for (final startYear in const [5, 6, 20]) {
        expect(growthPath(at(fade: true, startYear: startYear, years: 5)),
            List<double>.filled(5, 0.18));
      }
    });

    test('a starting rate below terminal rises, and still lands on it', () {
      final path = growthPath(at(fade: true, growth: 0.01, years: 6));
      expect(path.first, 0.01);
      expect(path.last, 0.025);
    });

    test('the projection uses the faded rates', () {
      final a = at(fade: true);
      final r = runDcf(base, a);
      final path = growthPath(a);
      expect(r.years.map((y) => y.revenueGrowth).toList(), path);
      var previous = base.revenue;
      for (var i = 0; i < path.length; i++) {
        expectClose(r.years[i].revenue, previous * (1 + path[i]));
        previous = r.years[i].revenue;
      }
    });

    test('fading lowers the value of a fast grower', () {
      expect(runDcf(base, at(fade: true)).intrinsicValuePerShare,
          lessThan(runDcf(base, at()).intrinsicValuePerShare));
    });
  });

  group('input guards', () {
    const base = BaseYearData(
      revenue: 1000,
      totalDebt: 100,
      cash: 100,
      shares: 100,
      currentPrice: 10,
    );

    test('terminal growth at or above WACC is refused', () {
      expect(
        () => runDcf(
            base,
            const DcfAssumptions(
              revenueGrowth: 0.05,
              operatingMargin: 0.2,
              taxRate: 0.2,
              daPct: 0.03,
              capexPct: 0.03,
              nwcPct: 0.02,
              wacc: 0.08,
              terminalGrowth: 0.08,
            )),
        throwsA(isA<DcfInputError>()),
      );
    });

    test('a zero share count is refused rather than producing infinity', () {
      expect(
        () => runDcf(
            const BaseYearData(
                revenue: 1000,
                totalDebt: 0,
                cash: 0,
                shares: 0,
                currentPrice: 10),
            const DcfAssumptions(
              revenueGrowth: 0.05,
              operatingMargin: 0.2,
              taxRate: 0.2,
              daPct: 0.03,
              capexPct: 0.03,
              nwcPct: 0.02,
              wacc: 0.08,
              terminalGrowth: 0.02,
            )),
        throwsA(isA<DcfInputError>()),
      );
    });
  });

  group('parity with the Python backend', () {
    late Map<String, dynamic> fixture;
    late List<dynamic> cases;

    setUpAll(() {
      final file = File('test/fixtures/parity_cases.json');
      expect(file.existsSync(), isTrue,
          reason: 'Run tools/generate_parity_fixtures.py with the backend up.');
      fixture = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
      cases = fixture['cases'] as List<dynamic>;
    });

    test('fixture covers a range of assumption combinations', () {
      expect(cases.length, greaterThanOrEqualTo(10));
    });

    test('every recorded case reproduces to within rounding', () {
      final failures = <String>[];

      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final label = c['label'] as String;

        final base =
            BaseYearData.fromJson(c['base_year'] as Map<String, dynamic>);
        final assumptions = DcfAssumptions.fromMap(
          (c['assumptions'] as Map<String, dynamic>)
              .map((k, v) => MapEntry(k, (v as num).toDouble())),
        );
        final expected = c['expected'] as Map<String, dynamic>;

        try {
          final result = runDcf(base, assumptions);

          void check(String field, double actual) {
            final want = (expected[field] as num).toDouble();
            final scale = math.max(1.0, want.abs());
            if ((actual - want).abs() / scale >= 1e-9) {
              failures.add('$label / $field: backend $want, dart $actual');
            }
          }

          check('intrinsic_value_per_share', result.intrinsicValuePerShare);
          check('upside_downside', result.upsideDownside);
          check('enterprise_value', result.enterpriseValue);
          check('equity_value', result.equityValue);
          check('terminal_value', result.terminalValue);
          check('pv_terminal_value', result.pvTerminalValue);
          check('pv_ufcf_sum', result.pvUfcfSum);
          check('tv_pct_of_ev', result.tvPctOfEv);
        } on DcfInputError catch (e) {
          failures.add('$label: dart engine refused inputs the backend accepted ($e)');
        }
      }

      expect(failures, isEmpty,
          reason: 'Dart and Python engines diverged:\n${failures.join('\n')}');
    });

    test('the honesty note reproduces the backend wording exactly', () {
      // Wording is duplicated in Dart so it can update mid-drag; this is the
      // guard against the two copies drifting apart.
      final mismatches = <String>[];

      for (final raw in cases) {
        final c = raw as Map<String, dynamic>;
        final assumptions = (c['assumptions'] as Map<String, dynamic>)
            .map((k, v) => MapEntry(k, (v as num).toDouble()));
        final expected = c['expected'] as Map<String, dynamic>;

        final built = buildHonestyNote(
          intrinsicValuePerShare:
              (expected['intrinsic_value_per_share'] as num).toDouble(),
          companyName: c['company_name'] as String,
          wacc: assumptions['wacc']!,
          terminalGrowth: assumptions['terminal_growth']!,
          equityRiskPremium: assumptions['equity_risk_premium'],
        );

        if (built != c['note']) {
          mismatches.add('${c['label']}:\n  backend: ${c['note']}\n  dart:    $built');
        }
      }

      expect(mismatches, isEmpty,
          reason: 'Honesty note wording drifted:\n${mismatches.join('\n\n')}');
    });
  });

  group('money and percent formatting matches Python', () {
    test('thousands separators and 2dp', () {
      expect(formatMoney(160.99), '160.99');
      expect(formatMoney(1234.5), '1,234.50');
      expect(formatMoney(1234567.891), '1,234,567.89');
      expect(formatMoney(0), '0.00');
      expect(formatMoney(-42.5), '-42.50');
    });

    test('percentages to 2dp', () {
      expect(formatPercent2(0.1059), '10.59%');
      expect(formatPercent2(0.025), '2.50%');
      expect(formatPercent2(0), '0.00%');
    });
  });
}
